# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment
minecraft_version=26.2
minecraft_version_range=[26.2,27)
neo_version=26.2.0.70

# Mod
mod_id=projectnublar
mod_name=Project Nublar
mod_author=Nyfaria
mod_license=CC0-1.0
mod_version=0.0.23
mod_group_id=net.dumbcode.projectnublar
mod_description=Dinosaurs
version=0.0.23
group=net.dumbcode.projectnublar

# Dependencies
geckolib_version=5.5.3
sbl_version=2.0.0
fabric_loader_version=0.19.5
fabric_version=0.159.0+26.2
