package net.dumbcode.projectnublar;

import net.dumbcode.projectnublar.datagen.GeneDataProvider;
import net.dumbcode.projectnublar.datagen.ModBlockStateProvider;
import net.dumbcode.projectnublar.datagen.ModLangProvider;
import net.dumbcode.projectnublar.datagen.ModLootTableProvider;
import net.dumbcode.projectnublar.datagen.ModRecipeProvider;
import net.dumbcode.projectnublar.datagen.ModSoundProvider;
import net.dumbcode.projectnublar.datagen.ModTagProvider;
import net.dumbcode.projectnublar.datagen.ModWorldGenProvider;
import net.dumbcode.projectnublar.platform.NeoForgePlatformHelper;
import net.dumbcode.projectnublar.platform.Services;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.data.event.GatherDataEvent;
import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;

@Mod(Constants.MODID)
public class ProjectNublarNeoForge {

    public ProjectNublarNeoForge(IEventBus modBus) {
        NeoForgePlatformHelper.setModBus(modBus);
        modBus.addListener(RegisterPayloadHandlersEvent.class,
            event -> ((NeoForgePlatformHelper) Services.PLATFORM).bindPayloads(event.registrar("1")));
        modBus.addListener(GatherDataEvent.Server.class, ProjectNublarNeoForge::onGatherDataServer);
        modBus.addListener(GatherDataEvent.Client.class, ProjectNublarNeoForge::onGatherDataClient);
        ProjectNublar.init();
    }

    private static void onGatherDataServer(GatherDataEvent.Server event) {
        event.addProvider(new ModRecipeProvider.Runner(event.getGenerator().getPackOutput(), event.getLookupProvider()));
        event.addProvider(new ModLootTableProvider(event.getGenerator().getPackOutput(), event.getLookupProvider()));
        event.addProvider(new ModSoundProvider(event.getGenerator().getPackOutput(), event.getLookupProvider()));
        event.addProvider(new ModWorldGenProvider(event.getGenerator().getPackOutput(), event.getLookupProvider()));
        event.addProvider(new ModTagProvider.BlockTag(event.getGenerator().getPackOutput(), event.getLookupProvider()));
        event.addProvider(new ModTagProvider.ItemTag(event.getGenerator().getPackOutput(), event.getLookupProvider()));
        event.addProvider(new ModTagProvider.EntityTypeTag(event.getGenerator().getPackOutput(), event.getLookupProvider()));
        event.addProvider(new GeneDataProvider(event.getGenerator().getPackOutput(), event.getLookupProvider()));
    }

    private static void onGatherDataClient(GatherDataEvent.Client event) {
        // item models are generated by ModBlockStateProvider.registerItemModels (the old
        // ModItemModelProvider was folded in there during the port)
        event.addProvider(new ModBlockStateProvider(event.getGenerator().getPackOutput()));
        event.addProvider(new ModLangProvider(event.getGenerator().getPackOutput()));
    }
}
